---
cases:
  sample.logging.ble_backend.nrf52833:
    path: samples/subsys/logging/ble_backend
    catalog: bluetooth
    platform_allow:
    - qemu_cortex_m3
    - qemu_x86
  sample.logging.multidomain.ipc_static_vrings:
    path: samples/subsys/logging/multidomain
    catalog: ipc
    platform_allow: nrf5340dk_nrf5340_cpuapp
    build_only: true
  kernel.logging.message_capture:
    path: tests/kernel/fatal/message_capture
    catalog: kernel
