---
cases:
  sample.logger.basic.dictionary:
    path: samples/subsys/logging/dictionary
    catalog: logging
    build_only: true
  sample.logger.basic.dictionary.fpu:
    path: samples/subsys/logging/dictionary
    catalog: logging
    extra_configs:
    - CONFIG_FPU=y
    build_only: true
    filter: CONFIG_CPU_HAS_FPU
  sample.logger.basic.dictionary.fpu.long_double:
    path: samples/subsys/logging/dictionary
    catalog: logging
    extra_configs:
    - CONFIG_FPU=y
    - CONFIG_CBPRINTF_PACKAGE_LONGDOUBLE=y
    build_only: true
    filter: CONFIG_CPU_HAS_FPU
  sample.logger.basic:
    path: samples/subsys/logging/logger
    catalog: logging
  sample.logger.rtt:
    path: samples/subsys/logging/logger
    catalog: logging
    extra_configs:
    - CONFIG_LOG_BACKEND_RTT=y
    - CONFIG_USE_SEGGER_RTT=y
    filter: CONFIG_HAS_SEGGER_RTT
  sample.logger.syst:
    path: samples/subsys/logging/syst
    catalog: logging
    platform_allow: mps2_an385 sam_e70_xplained
