---
cases:
  sample.application_development.code_relocation_nocopy:
    path: samples/application_development/code_relocation_nocopy
    catalog: linker
    platform_allow:
    - qemu_cortex_m3
    - nrf5340dk_nrf5340_cpuapp
  sample.application_development.sysbuild.with_mcuboot:
    path: samples/application_development/sysbuild/with_mcuboot
    catalog: mcuboot
    platform_allow:
    - reel_board
    - nrf52840dk_nrf52840
