---
cases:
  sample.application_development.code_relocation_nocopy:
    path: samples/application_development/code_relocation_nocopy
    catalog: linker
    platform_allow:
    - qemu_cortex_m3
    - nrf5340dk_nrf5340_cpuapp
  sample.application_development.sysbuild.with_mcuboot:
    path: samples/application_development/sysbuild/with_mcuboot
    catalog: mcuboot
    sysbuild: true
    platform_allow:
    - reel_board
    - nrf52840dk_nrf52840
  tests.application_development.code_relocation:
    path: tests/application_development/code_relocation
    catalog: linker
    extra_configs:
    - CONFIG_RELOCATE_TO_ITCM=y
    filter: not CONFIG_CPU_HAS_NXP_MPU and CONFIG_MINIMAL_LIBC and dt_chosen_enabled("zephyr,itcm")
    arch_allow: arm
  tests.application_development.code_relocation_kinetis:
    path: tests/application_development/code_relocation
    catalog: linker
    extra_configs:
    - CONFIG_RELOCATE_TO_ITCM=y
    - CONFIG_MPU_ALLOW_FLASH_WRITE=y
    filter: CONFIG_CPU_HAS_NXP_MPU and CONFIG_MINIMAL_LIBC and dt_chosen_enabled("zephyr,itcm")
    arch_allow: arm
  tests.application_development.code_relocation.no_itcm:
    path: tests/application_development/code_relocation
    catalog: linker
    filter: not CONFIG_CPU_HAS_NXP_MPU and not dt_chosen_enabled("zephyr,itcm")
    arch_allow: arm
    platform_allow:
    - qemu_cortex_m3
    - mps2_an385
    - sam_e70_xplained
  tests.application_development.code_relocation.riscv:
    path: tests/application_development/code_relocation
    catalog: linker
    extra_args: CONF_FILE="prj_riscv.conf"
    platform_allow:
    - qemu_riscv32
    - qemu_riscv64
  tests.application_development.code_relocation.xtensa:
    path: tests/application_development/code_relocation
    catalog: linker
    extra_args: CONF_FILE="prj_xtensa.conf"
    platform_allow: qemu_xtensa
