---
cases:
  crypto.rand32:
    path: tests/crypto/rand32
    catalog: crypto random security
    min_ram: 16
  crypto.rand32.random_sw_systimer:
    path: tests/crypto/rand32
    catalog: crypto random security
    extra_args: CONF_FILE=prj_sw_random_systimer.conf
    min_ram: 16
