---
cases:
  system.settings.littlefs.base64:
    path: tests/subsys/settings/littlefs/base64
    catalog: settings_fs filesystem
    platform_whitelist: nrf52840_pca10056 native_posix native_posix_64
