---
cases:
  sample.nvs.basic:
    path: samples/subsys/nvs
    catalog: settings
    depends_on: nvs
    platform_exclude: qemu_x86
  sample.subsys.settings:
    path: samples/subsys/settings
    catalog: settings
    platform_allow: qemu_x86 native_posix native_posix_64
