---
cases:
  system.settings.littlefs:
    path: tests/subsys/settings/littlefs/raw
    catalog: settings_fs settings_littlefs
    platform_whitelist: nrf52840_pca10056 native_posix native_posix_64
