---
cases:
  system.settings.functional.nvs:
    path: tests/subsys/settings/functional/nvs
    catalog: settings_nvs
  system.settings.functional.nvs.dk:
    path: tests/subsys/settings/functional/nvs
    catalog: settings_nvs
    extra_args: OVERLAY_CONFIG=mpu.conf
  system.settings.nvs:
    path: tests/subsys/settings/nvs/raw
    catalog: settings_nvs
    depends_on: nvs
    min_ram: 32
