---
cases:
  system.settings.fcb.raw:
    path: tests/subsys/settings/fcb
    catalog: settings_fcb
    platform_allow:
    - nrf52840dk_nrf52840
    - nrf52dk_nrf52832
    - native_posix
    - native_posix_64
  system.settings.fcb:
    path: tests/subsys/settings/fcb_init
    catalog: settings_intialization_fcb
    platform_allow:
    - nrf52840dk_nrf52840
    - nrf52dk_nrf52832
  system.settings.file.raw:
    path: tests/subsys/settings/file
    catalog:
    - settings_file
    - settings_file_littlefs
    platform_allow:
    - nrf52840dk_nrf52840
    - native_posix
    - native_posix_64
  system.settings.functional.fcb:
    path: tests/subsys/settings/functional/fcb
    catalog: settings_fcb
    platform_allow:
    - nrf52840dk_nrf52840
    - nrf52dk_nrf52832
    - native_posix
    - native_posix_64
  system.settings.functional.fcb.chosen:
    path: tests/subsys/settings/functional/fcb
    catalog: settings_fcb
    extra_args: DTC_OVERLAY_FILE=./chosen.overlay
    platform_allow:
    - native_posix
    - native_posix_64
  system.settings.file:
    path: tests/subsys/settings/functional/file
    catalog: settings_file
    platform_allow:
    - nrf52840dk_nrf52840
    - nrf52dk_nrf52832
    - native_posix
    - native_posix_64
  system.settings.functional.nvs:
    path: tests/subsys/settings/functional/nvs
    catalog: settings_nvs
    platform_allow:
    - qemu_x86
    - native_posix
    - native_posix_64
  system.settings.functional.nvs.chosen:
    path: tests/subsys/settings/functional/nvs
    catalog: settings_nvs
    extra_args: DTC_OVERLAY_FILE=./chosen.overlay
    platform_allow:
    - native_posix
    - native_posix_64
  system.settings.functional.nvs.dk:
    path: tests/subsys/settings/functional/nvs
    catalog: settings_nvs
    extra_args: OVERLAY_CONFIG=mpu.conf
    platform_allow:
    - nrf52840dk_nrf52840
    - nrf52dk_nrf52832
  system.settings.nvs:
    path: tests/subsys/settings/nvs
    catalog: settings_nvs
    depends_on: nvs
    min_ram: 32
