---
cases:
  system.settings.littlefs.raw:
    path: tests/subsys/settings/littlefs/raw
    catalog: settings_fs settings_littlefs
    platform_allow: nrf52840dk_nrf52840 native_posix native_posix_64
