---
cases:
  system.settings.fcb.base64:
    path: tests/subsys/settings/fcb/base64
    catalog: settings_fcb
  system.settings.fcb.raw:
    path: tests/subsys/settings/fcb/raw
    catalog: settings_fcb
  system.settings.functional.fcb:
    path: tests/subsys/settings/functional/fcb
    catalog: settings_fcb
