---
cases:
  system.settings.functional.fcb:
    path: tests/subsys/settings/functional/fcb
    catalog: settings_fcb
    platform_whitelist: nrf52840_pca10056 nrf52_pca10040 native_posix native_posix_64
