---
cases:
  system.settings.fcb.raw:
    path: tests/subsys/settings/fcb/raw
    catalog: settings_fcb
    extra_configs:
    - CONFIG_ARM_MPU=n
    - CONFIG_STDOUT_CONSOLE=y
    platform_allow: nrf52840dk_nrf52840 nrf52dk_nrf52832
  system.settings.fcb.raw_native_posix:
    path: tests/subsys/settings/fcb/raw
    catalog: settings_fcb
    platform_allow: native_posix native_posix_64
  system.settings.functional.fcb:
    path: tests/subsys/settings/functional/fcb
    catalog: settings_fcb
    platform_allow: nrf52840dk_nrf52840 nrf52dk_nrf52832 native_posix native_posix_64
  system.settings.functional.fcb.chosen:
    path: tests/subsys/settings/functional/fcb
    catalog: settings_fcb
    extra_args: DTC_OVERLAY_FILE=./chosen.overlay
    platform_allow: native_posix native_posix_64
