---
cases:
  system.settings.functional.nvs:
    path: tests/subsys/settings/functional/nvs
    catalog: settings_nvs
    platform_allow: qemu_x86 native_posix native_posix_64
  system.settings.functional.nvs.chosen:
    path: tests/subsys/settings/functional/nvs
    catalog: settings_nvs
    extra_args: DTC_OVERLAY_FILE=./chosen.overlay
    platform_allow: native_posix native_posix_64
  system.settings.functional.nvs.dk:
    path: tests/subsys/settings/functional/nvs
    catalog: settings_nvs
    extra_args: OVERLAY_CONFIG=mpu.conf
    platform_allow: nrf52840dk_nrf52840 nrf52dk_nrf52832
  system.settings.nvs:
    path: tests/subsys/settings/nvs/raw
    catalog: settings_nvs
    depends_on: nvs
    min_ram: 32
