---
cases:
  system.settings.littlefs.base64:
    path: tests/subsys/settings/littlefs/base64
    catalog: settings_fs filesystem
    extra_configs:
    - CONFIG_STDOUT_CONSOLE=y
    - CONFIG_ARM_MPU=n
    platform_allow: nrf52840dk_nrf52840
  system.settings.littlefs.base64_native_posix:
    path: tests/subsys/settings/littlefs/base64
    catalog: settings_fs filesystem
    platform_allow: native_posix native_posix_64
