---
cases:
  system.settings.littlefs.raw:
    path: tests/subsys/settings/littlefs/raw
    catalog: settings_fs settings_littlefs
    extra_configs:
    - CONFIG_STDOUT_CONSOLE=y
    - CONFIG_ARM_MPU=n
    platform_allow: nrf52840dk_nrf52840
  system.settings.littlefs.raw_native_posix:
    path: tests/subsys/settings/littlefs/raw
    catalog: settings_fs settings_littlefs
    platform_allow: native_posix native_posix_64
